In [1]:
import pandas as pd
import numpy as np
import polars as pl
import os
import awpy
from awpy import Demo
from demoparser2 import DemoParser

In [2]:
file_path = r'C:\Users\bayli\Documents\Git Projects\test_demos\natus-vincere-vs-faze-m1-inferno.dem'

In [50]:
dem = Demo(file_path)
dem.parse(player_props=["armor_value", "pitch", "yaw", "velocity_X", "velocity_Y", "velocity_Z", "flash_duration"])
ticks_df = dem.ticks
ticks_df = ticks_df.to_pandas()
ticks_df.rename(columns={'steamid': 'user_steamid'}, inplace=True)

this_file_flashes = dem.events.get('flashbang_detonate', pl.DataFrame())
if this_file_flashes is not None and len(this_file_flashes) > 0:
    this_file_flashes = this_file_flashes.with_columns(
        this_file_flashes['user_steamid'].cast(pl.Utf8)
    )
this_file_flashes = this_file_flashes.to_pandas()
this_file_flashes['user_steamid'] = this_file_flashes['user_steamid'].astype('uint64')

this_file_he = dem.events.get('hegrenade_detonate', pl.DataFrame())
if this_file_he is not None and len(this_file_he) > 0:
    this_file_he = this_file_he.with_columns(
        this_file_he['user_steamid'].cast(pl.Utf8)
    )
this_file_he = this_file_he.to_pandas()
this_file_he['user_steamid'] = this_file_he['user_steamid'].astype('uint64')

this_file_infernos = dem.events.get('inferno_startburn', pl.DataFrame())
if this_file_infernos is not None and len(this_file_infernos) > 0:
    this_file_infernos = this_file_infernos.with_columns(
        this_file_infernos['user_steamid'].cast(pl.Utf8)
    )
this_file_infernos = this_file_infernos.to_pandas()
this_file_infernos['user_steamid'] = this_file_infernos['user_steamid'].astype('uint64')

this_file_smoke = dem.events.get('smokegrenade_detonate', pl.DataFrame())
if this_file_smoke is not None and len(this_file_smoke) > 0:
    this_file_smoke = this_file_smoke.with_columns(
        this_file_smoke['user_steamid'].cast(pl.Utf8)
    )
this_file_smoke = this_file_smoke.to_pandas()
this_file_smoke['user_steamid'] = this_file_smoke['user_steamid'].astype('uint64')

In [ ]:
pd.set_option('display.max_columns', None)
this_file_smoke

,ct_side,entityid,t_side,tick,user_X,user_Y,user_Z,user_armor,user_flash_duration,user_health,user_place,user_name,user_pitch,user_steamid,user_side,user_velocity_X,user_velocity_Y,user_velocity_Z,user_yaw,x,y,z
0,ct,455,t,8966,1114.823975,540.093445,112.414360,0,0.0,100,Middle,karrigan,3.596985,76561197989430253,t,-13.507812,-181.257812,-91.666992,13.118362,1467.357666,689.796692,126.853500
1,ct,459,t,9338,1922.106201,-182.031738,260.031250,0,0.0,100,Apartments,broky,14.462814,76561198201620490,t,-133.273438,2.023438,0.000000,33.735580,2256.358154,943.683594,156.947021
2,ct,340,t,15019,1536.532593,122.866554,132.031250,100,0.0,100,TopofMid,b1t,2.311584,76561198246607476,ct,214.429688,107.797363,0.000000,118.482391,1160.353760,482.692322,111.979645
3,ct,345,t,15248,779.292358,2389.676270,136.031464,100,0.0,100,BombsiteB,jL,0.748108,76561198176878303,ct,0.000000,0.000000,0.000000,-125.425072,403.050507,1908.002686,138.031219
4,ct,354,t,16810,1135.125488,587.967896,117.963425,100,0.0,100,Middle,karrigan,-15.509949,76561197989430253,t,0.000000,0.000000,0.000000,-44.985229,1491.468140,1182.445679,179.118057
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,ct,424,t,177152,932.511169,384.538544,95.439667,85,0.0,100,SecondMid,b1t,-3.779984,76561198246607476,t,-22.960938,84.189453,2.202637,23.820068,1467.736816,1045.966431,158.023636
114,ct,737,t,178266,190.315659,2868.777588,161.531265,100,0.0,100,BombsiteB,frozen,1.715927,76561198068422762,ct,-129.056641,-140.218750,0.000000,-33.582794,788.637817,2336.488770,138.031464
115,ct,925,t,178419,762.801819,1975.832642,136.031265,86,0.0,100,Banana,jL,7.590179,76561198176878303,t,-79.683594,-13.835938,0.000000,99.471588,962.146912,2726.749756,134.422516
116,ct,477,t,178561,1685.772705,46.152416,130.304474,100,0.0,100,BombsiteA,broky,-10.868225,76561198201620490,ct,110.585938,38.211914,-1.179688,-29.981689,1167.895020,451.275757,112.582954
117,ct,493,t,178748,956.468750,711.968628,105.976616,90,0.0,100,Middle,iM,0.557220,76561198050250233,t,0.000000,0.000000,0.000000,-83.060417,1448.528809,940.674133,148.103271

In [51]:
mapping_df = ticks_df.merge(
    this_file_smoke,
    on = ['user_steamid', 'tick'],
    how='left'
).rename(columns={'x':'x_smoke', 'y':'y_smoke', 'z':'z_smoke'}).drop(columns=['ct_side', 'entityid', 't_side', 'user_X', 'user_Y', 'user_Z', 'user_armor', 'user_flash_duration', 'user_health', 'user_place', 
                                                     'user_name', 'user_pitch', 'user_side', 'user_velocity_X',	'user_velocity_Y', 'user_velocity_Z',
                                                     'user_yaw'])

mapping_df = mapping_df.merge(
    this_file_infernos,
    on = ['user_steamid', 'tick'],
    how='left'
).rename(columns={'x':'x_infernos', 'y':'y_infernos', 'z':'z_infernos'}).drop(columns=['ct_side', 'entityid', 't_side', 'user_X', 'user_Y', 'user_Z', 'user_armor', 'user_flash_duration', 'user_health', 'user_place', 
                                                     'user_name', 'user_pitch', 'user_side', 'user_velocity_X',	'user_velocity_Y', 'user_velocity_Z',
                                                     'user_yaw'])

mapping_df = mapping_df.merge(
    this_file_he,
    on = ['user_steamid', 'tick'],
    how='left'
).rename(columns={'x':'x_he', 'y':'y_he', 'z':'z_he'}).drop(columns=['ct_side', 'entityid', 't_side', 'user_X', 'user_Y', 'user_Z', 'user_armor', 'user_flash_duration', 'user_health', 'user_place', 
                                                     'user_name', 'user_pitch', 'user_side', 'user_velocity_X',	'user_velocity_Y', 'user_velocity_Z',
                                                     'user_yaw'])

mapping_df = mapping_df.merge(
    this_file_flashes,
    on = ['user_steamid', 'tick'],
    how='left'
).rename(columns={'x':'x_flashes', 'y':'y_flashes', 'z':'z_flashes'}).drop(columns=['ct_side', 'entityid', 't_side', 'user_X', 'user_Y', 'user_Z', 'user_armor', 'user_flash_duration', 'user_health', 'user_place', 
                                                     'user_name', 'user_pitch', 'user_side', 'user_velocity_X',	'user_velocity_Y', 'user_velocity_Z',
                                                     'user_yaw'])

In [60]:
filtered = mapping_df[mapping_df['round_num'] == 4]
pd.set_option('display.max_columns', None)
filtered

,health,flash_duration,place,armor,side,pitch,X,yaw,Y,velocity_X,Z,velocity_Y,velocity_Z,tick,user_steamid,name,round_num,x_smoke,y_smoke,z_smoke,x_infernos,y_infernos,z_infernos,x_he,y_he,z_he,x_flashes,y_flashes,z_flashes
251380,100,0.0,,0,t,8.372269,-1675.619995,75.129669,351.695007,0.00000,-29.900024,0.000,0.00000,30197,76561197991272318,ropz,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
251381,100,0.0,,0,t,-1.108932,-1662.180054,-36.983414,288.761993,0.00000,-63.868774,0.000,0.00000,30197,76561197997351207,rain,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
251382,100,0.0,,0,t,4.598114,-1520.060059,32.190628,430.890991,0.00000,-63.868774,0.000,0.00000,30197,76561198201620490,broky,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
251383,100,0.0,,74,ct,7.273987,2493.000000,75.791245,2090.000000,220.46875,132.813110,117.875,-9.34668,30197,76561199063068840,w0nderful,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
251384,100,0.0,,0,t,1.759872,-1657.229980,7.507782,419.576996,0.00000,-63.868774,0.000,0.00000,30197,76561198068422762,frozen,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342215,100,0.0,Banana,100,ct,9.747620,662.968750,-38.817780,1880.033325,0.00000,170.031250,0.000,0.00000,39284,76561198013243326,Aleksib,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342216,100,0.0,Pit,100,ct,-3.561630,2458.032471,158.841705,-137.246948,0.00000,97.622681,0.000,0.00000,39284,76561198246607476,b1t,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342217,94,0.0,Ruins,100,ct,4.707977,1179.409180,-40.531311,3077.813232,187.62500,128.031250,0.000,0.00000,39284,76561198176878303,jL,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342218,0,0.0,Banana,0,t,0.560989,423.748291,117.483673,1761.959839,0.00000,134.031219,0.000,0.00000,39284,76561197989430253,karrigan,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342219,100,0.0,BombsiteA,100,ct,9.411499,1704.875610,175.970764,131.966614,0.00000,184.031250,0.000,0.00000,39284,76561198050250233,iM,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
filtered.to_csv("round_4_mapping.csv", index=False)